# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  cpp_scenegraph_config = debug
endif
ifeq ($(config),release)
  cpp_scenegraph_config = release
endif

PROJECTS := cpp-scenegraph

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

cpp-scenegraph:
ifneq (,$(cpp_scenegraph_config))
	@echo "==== Building cpp-scenegraph ($(cpp_scenegraph_config)) ===="
	@${MAKE} --no-print-directory -C . -f cpp-scenegraph.make config=$(cpp_scenegraph_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f cpp-scenegraph.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   cpp-scenegraph"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"